#training set of strings
#it is a list of query, api_type

training_set = [("Let's meet up on Friday at 3 p.m.", "calendar"),
								("Can we have a meeting next week", "calendar"),
								("Benedict, schedule a meeting for next Tuesday", "calendar"),
								("Next Wednesday let's have a conference", "calendar"),
								("Can you schedule me a meeting for tomorrow", "calendar"),
								("Could you find a time that works for all of us", "calendar"),
								("Can we have a weekly meeting on Thursdays", "calendar"),
								("Would you be available after 2pm on Wednesday", "calendar"),
								("Lets meet tomorrow at 12", "calendar"),
								("Set up a meeting for tomorrow at 12", "calendar"),
								("Let's meet later", "calendar"),
								("Schedule a meeting tomorrow.", "calendar"),
								("What is the phase of the moon", "wolfram"),
								("Why are dogs", "google"),
								("What is the rate of expansion of the universe", "wolfram"),
								("When is my birthday", "google"),
								("Why do dogs have feet", "google"),
								("What are the biggest problems facing humanity", "google"),
								("When can I see my children again", "google"),
								("What are these spots on my genitals", "google"),
								("Why do birds suddenly appear", "google"),
								("Where is a good place to get Chinese food", "google"),
								("Random pokemon curve", "wolfram"),
								("Open up a document", "google_doc")]
