#training set of strings
#it is a list of query, api_type

training_set = [("Let's meet up on Friday at 3 p.m.", "calendar"),
								("Can we have a meeting next week", "calendar"),
								("Benedict, schedule a meeting for next Tuesday", "calendar"),
								("Next Wednesday let's have a conference", "calendar"),
								("Can you schedule me a meeting for tomorrow", "calendar"),
								("Could you find a time that works for all of us", "calendar"),
								("Can we have a weekly meeting on Thursdays", "calendar"),
								("Lets meet tomorrow at 12", "calendar"),
								("Set up a meeting for tomorrow at 12", "calendar"),
								("Let's meet later", "calendar"),
								("Can we meet tomorrow at 5 pm", "calendar"),
								("Can you schedule us a meeting for tomorrow at 3", "calendar"),
								("Lets meet tomorrow at 8 am", "calendar"),
								("Schedule a meeting tomorrow.", "calendar"),
								("Schedule meeting", "calendar"),
								("Schedule an appointment", "calendar"),
								("Schedule an appointment today", "calendar"),
								("Schedule an appointment for tomorrow", "calendar"),
								("schedule next week at 9 a.m.", "calendar"),
								("schedule next week for 9 p.m.", "calendar"),
								("Benedict, set an appointment for tomorrow at 7", "calendar"),



								("Benedict, find us a time that works", "schedule_suggest"),
								("when are all of us free", "schedule_suggest"),
								("when are all of us free next week", "schedule_suggest"),
								("when are all of us free tomorrow", "schedule_suggest"),
								("when are all of us free today", "schedule_suggest"),
								("Let's find a time that works", "schedule_suggest"),
								("find a time that works for me", "schedule_suggest"),
								("find a time that works for all of us", "schedule_suggest"),
								("find a time that works for us", "schedule_suggest"),
								("find us time a meeting for next week", "schedule_suggest"),
								("tell us when we are free tomorrow", "schedule_suggest"),
								("show us our potential meeting times", "schedule_suggest"),
								("show us our potential meeting times for next week", "schedule_suggest"),



								("open up a doc", "google_docs"),
								("open up a document", "google_docs"),
								("open up a Google document", "google_docs"),
								("pull up a document", "google_docs"),
								("open me a document", "google_docs"),
								("open up a dock", "google_docs"),
								("open up a dog", "google_docs"),
								("open a notepad", "google_docs"),
								("open writing document", "google_docs"),
								("open us a document", "google_docs"),
								("display document", "google_docs"),
								("generate a document", "google_docs"),
								("Benedict, can you open up a document", "google_docs"),
								("can you open up a document", "google_docs"),
								("please launch a document", "google_docs"),
								("show me a dock", "google_docs"),
								("pull us up a document", "google_docs"),
								("Benedict, open me a document", "google_docs"),
								("Benedict, show me a dock", "google_docs"),



								("What is the phase of the moon", "wolfram"),
								("twenty two plus five", "wolfram"),
								("What's the weather in Isla Vista", "wolfram"),
								("What is a galaxy", "wolfram"),
								("Where is Mexico", "wolfram"),
								("Where is Chicago", "wolfram"),
								("Where is Louisiana", "wolfram"),
								("Where Los Angeles", "wolfram"),
								("Who Obama", "wolfram"),
								("Who is Kendrick Lamar", "wolfram"),
								("Who is the president of France", "wolfram"),
								("Who is the leader of Russia", "wolfram"),
								("What is the phase of the moon", "wolfram"),
								("What is the rate of expansion of the universe", "wolfram"),
								("What weather", "wolfram"),
								("what is the weather", "wolfram"),
								("what is the weather in New York", "wolfram"),
								("what is the weather here", "wolfram"),
								("what is the weather tomorrow", "wolfram"),
								("what is the weather next week", "wolfram"),
								("what is two times two", "wolfram"),
								("what is 100 plus 30", "wolfram"),
								("what is the integral of e to the x", "wolfram"),
								("what is Stoke's theorem", "wolfram"),
								("What is the derivative of x squared", "wolfram"),
								("How long was the one hundred year's war", "wolfram"),
								("random pokemon curve", "wolfram"),
								("random integer from 0 to 100", "wolfram"),
								("when was the declaration of independence signed", "wolfram"),
								("what is the phase of the moon", "wolfram")
								("what is the phase of the moon tomorrow", "wolfram")
								("what is the phase of the moon next week", "wolfram")
								("Graph x squared", "wolfram"),
								("Graph the function sign", "wolfram"),
								("What is cosine of pie", "wolfram"),
								("What is cosine of pi", "wolfram"),
								("What is the natural log of e", "wolfram"),
								("What is the largest state in the United States", "wolfram"),
								("What is Italy's GDP", "wolfram"),
								("how many grams are in ounce", "wolfram"),
								("what is the conversion of pounds to kilograms", "wolfram"),



								("Eiffel tower", "wikipedia"),
								("the beatles", "wikipedia"),
								("Mickey mouse", "wikipedia"),
								("coca cola", "wikipedia"),
								("Obama", "wikipedia"),
								("Black Hole", "wikipedia"),
								("General Relativity", "wikipedia"),
								("mathematical set", "wikipedia"),
								("the trivial topology", "wikipedia"),
								("Eiffel Tower", "wikipedia"),
								("the Magna Carta", "wikipedia"),
								("Albert Einstein", "wikipedia"),
								("Michael Jackson", "wikipedia"),
								("New York City", "wikipedia"),
								("meteorology", "wikipedia"),
								("webRTC", "wikipedia"),
								("Amazon AWS", "wikipedia"),
								("Star Trek", "wikipedia"),
								("Monty python's flying circus", "wikipedia"),
								("the golden gate bridge", "wikipedia"),
								("the statue of liberty", "wikipedia"),
								("the movie pulp fiction", "wikipedia"),
								("dogs", "wikipedia"),



								("Why are dogs", "google"),
								("When is my birthday", "google"),
								("Why do dogs have feet", "google"),
								("is God real", "google"),
								("Miley Cyrus twerk video", "google"),
								("where can I find a bible study group in my area", "google"),
								("at what age do boys start their period", "google"),
								("why is bing a bad search engine", "google"),
								("how can I tell my son is on drugs", "google"),
								("what time is the lakers game on tonight", "google"),
								("how does the internet work", "google"),
								("where does the Michael Cera fan club meet", "google"),
								("how do I clean the spots out of my underwear", "google"),
								("what is Rick rolling", "google"),
								("who is Luke's father", "google"),
								("how do you make special brownies", "google"),
								("when should I use an Oxford comma", "google"),
								("how do I prevent my parents from talking about the birds and the bees", "google"),
								("when will hoverboards exist", "google"),
								("where did the dinosaurs go", "google"),
								("what is a blue waffle", "google"),
								("how to avoid paying taxes", "google"),
								("What are the biggest problems facing humanity", "google"),
								("When can I see my children again", "google"),
								("what does it mean to drop the kids off at the pool", "google"),
								("What are these spots on my genitals", "google"),
								("Why do birds suddenly appear", "google"),
								("where can I meet girls", "google"),
								("how special do you need to be to be in the special olympics", "google"),
								("where do babies come from", "google"),
								("Where is a good place to get Chinese food", "google"),
								("how often should I go to the dentist", "google"),
								("how do I make friends", "google"),
								("do girls fart", "google"),
								("how do I ask out Becky from fourth period", "google")]

